(function(){
  'use strict';
  const {PAIRS,mockBacktest}=window.StatArb;
  const soybeanPair=PAIRS.find(p=>p.id==='m-rm');if(soybeanPair)soybeanPair.name='M–RM';
  const $=s=>document.querySelector(s),app=$('#app'),toast=$('#toast');
  const params={startDate:'2021-01-01',endDate:'2025-05-15',initialCapital:1000000,positionPct:.5,lookbackDays:252,entryMode:'quantile',entryUpper:.95,entryLower:.05,entryCustomValue:1,exitMode:'quantile',exitQuantile:.5,exitCustomValue:0,drawdownLimit:.08,volatilityLimit:.18,adjustment:'ratio-forward',frequency:'daily',orderTime:'open15',minuteInterval:15,direction:'both',transactionCost:1.5,riskFreeRate:0};
  const state={view:'workbench',pairId:'ru-nr',collapsed:false,bottomTab:'performance',range:'1Y',search:'',running:false,dirty:false,result:null,selectedTrade:null,hoverTrade:null,tradeStatus:'all',chartMode:'kline',upperHeight:0,sidebarWidth:286};
  const pct=(v,d=2)=>`${v>=0?'+':'−'}${Math.abs(v*100).toFixed(d)}%`,num=(v,d=2)=>v==null?'—':v.toFixed(d),pair=()=>PAIRS.find(p=>p.id===state.pairId)||PAIRS[0],pairSubtitle=p=>`${p.legA} ${p.operator||'−'}${p.showCoefficient?` ${p.beta.toFixed(2)} ×`:''} ${p.legB} · 日线`;
  function notify(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
  function readRecords(){try{const raw=localStorage.getItem('stat-arb-runs-v1');const rows=raw?JSON.parse(raw):[];return Array.isArray(rows)?rows:[]}catch(e){return[]}}
  function saveRecord(result){try{const records=readRecords().filter(x=>x.pairId!==state.pairId||x.params?.startDate!==params.startDate||x.params?.endDate!==params.endDate);const record={schemaVersion:1,id:`run-${Date.now()}-${Math.random().toString(16).slice(2,7)}`,createdAt:new Date().toISOString(),status:'completed',params:structuredClone(params),selectedPairIds:[state.pairId],results:[{pairId:state.pairId,status:'success',error:null,...structuredClone(result)}]};localStorage.setItem('stat-arb-runs-v1',JSON.stringify([record,...records].slice(0,20)))}catch(e){notify('本次回测完成，但历史记录暂不可用')}}
  function updateNav(){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',(state.view==='runs'&&b.dataset.nav==='runs')||(state.view==='workbench'&&b.dataset.nav==='workbench')))}
  function run(showToast=false){if(!params.startDate||!params.endDate||params.startDate>params.endDate){notify('请检查回测起止日期');return}state.running=true;render();setTimeout(()=>{try{state.result=mockBacktest(params,state.pairId);saveRecord(state.result);state.dirty=false;if(showToast)notify('策略回测已更新')}catch(err){notify(err.message||'回测配置不可用')}finally{state.running=false;render()}},showToast?420:20)}
  function filteredPairs(){const q=state.search.trim().toLowerCase();return PAIRS.filter(p=>!q||`${p.name}${p.legA}${p.legB}${p.category}`.toLowerCase().includes(q))}
  function render(){
    updateNav();
    if(state.view==='runs'){renderRecords();return}
    const p=pair(),r=state.result;
    app.innerHTML=`<div class="workspace" style="--sidebar:${state.sidebarWidth}px;${state.upperHeight?`--upper-height:${state.upperHeight}px`:''}">
      <section class="upper-panel ${state.collapsed?'collapsed':''}">
        <aside class="pair-sidebar">
          <div class="sidebar-rail"><button class="collapse-btn" id="expandSidebar" aria-label="展开套利组合">›</button><span class="rail-label">套利组合</span></div>
          <div class="sidebar-content">
            <div class="sidebar-title"><div><h2>套利组合</h2><p>选择组合查看价差与信号</p></div><button class="collapse-btn" id="collapseSidebar" aria-label="收起套利组合">‹</button></div>
            <div class="pair-search"></div>
            <div class="list-label">推荐套利对 · ${filteredPairs().length}</div>
            <div class="pair-list">${filteredPairs().map((x,i)=>`<button class="pair-item ${x.id===p.id?'active':''}" data-pair="${x.id}"><i class="pair-dot" style="background:${x.color}"></i><span class="pair-info"><b>${x.name}</b><small>${x.formula} · ${x.category}</small></span><span class="pair-change ${i%4===3?'negative':''}">${i%4===3?'−':'+'}${(1.18+i*.37).toFixed(2)}%</span></button>`).join('')}</div>
            <div class="sidebar-card"><label>当前策略</label><strong>分位数均值回归</strong><p>观察窗口 ${params.lookbackDays} 日<br>开仓 ${Math.round(params.entryLower*100)}% / ${Math.round(params.entryUpper*100)}% · 平仓中位数</p></div>
          </div>
        </aside>
        <div class="column-resizer" id="columnResizer" role="separator" aria-orientation="vertical" aria-label="调整套利组合栏宽度"></div>
        <div class="chart-shell">
          <div class="chart-toolbar"><div class="symbol-block"><div class="symbol-title">${p.name}<span class="market-chip">价差</span></div><div class="symbol-subtitle">${pairSubtitle(p)}</div></div><div class="ohlc">O 1,248.6　H 1,276.4　L 1,231.2　C 1,269.8 <span>+1.72%</span></div><div class="toolbar-spacer"></div><button class="toolbar-btn ${state.chartMode==='kline'?'active':''}" data-chart-mode="kline">K线</button><button class="toolbar-btn ${state.chartMode==='band'?'active':''}" data-chart-mode="band">价差带</button></div>
          <div class="chart-wrap"><canvas id="kline"></canvas><div class="chart-overlay"><strong>Spread · ${p.name}</strong>${state.chartMode==='band'?'<span class="band-legend"><i></i> MA 20　±2σ</span>':state.chartMode==='indicator'?'<span class="indicator-legend">动量指标 · 20 日</span>':'日线'}　<span class="positive">● B 买入　<span class="sell-key">● S 卖出</span></span></div><div class="trade-tooltip" id="tradeTooltip"></div><div class="price-tag">1,269.8</div></div>
          <div class="rangebar">${['1M','3M','6M','1Y','3Y','全部'].map(x=>`<button data-range="${x}" class="${state.range===x?'active':''}">${x}</button>`).join('')}<span>${params.startDate} — ${params.endDate}　UTC+8</span></div>
        </div>
      </section>
      <div class="row-resizer" id="rowResizer" role="separator" aria-orientation="horizontal" aria-label="调整图表和策略测试器高度"><span></span></div>
      <section class="tester">
        <div class="config-toolbar"><div class="config-control config-dates"><label>回测区间</label><input id="cfgStart" type="date" value="${params.startDate}"><span>—</span><input id="cfgEnd" type="date" value="${params.endDate}"></div><label class="config-control"><span>初始资金</span><select id="cfgCapital"><option value="500000" ${params.initialCapital===500000?'selected':''}>¥500,000</option><option value="1000000" ${params.initialCapital===1000000?'selected':''}>¥1,000,000</option><option value="5000000" ${params.initialCapital===5000000?'selected':''}>¥5,000,000</option></select></label><label class="config-control"><span>策略配置</span><select id="cfgStrategy"><option>分位数均值回归</option><option>标准差均值回归</option></select></label><label class="config-control"><span>方向</span><select id="cfgDirection"><option value="both" ${params.direction==='both'?'selected':''}>双向</option><option value="long" ${params.direction==='long'?'selected':''}>仅做多</option><option value="short" ${params.direction==='short'?'selected':''}>仅做空</option></select></label><label class="config-control"><span>交易成本</span><span class="config-suffix"><input id="cfgCost" type="number" min="0" max="50" step="0.1" value="${params.transactionCost}"><i>万分</i></span></label><label class="config-control"><span>复权方式</span><select id="cfgAdjustment"><option value="ratio-forward" ${params.adjustment==='ratio-forward'?'selected':''}>比值前复权</option><option value="ratio-backward" ${params.adjustment==='ratio-backward'?'selected':''}>比值后复权</option><option value="none" ${params.adjustment==='none'?'selected':''}>不复权</option></select></label><button class="apply-config ${state.dirty?'pending':''}" id="applyConfig" ${state.running?'disabled':''}>${state.running?'计算中':state.dirty?'应用配置':'已应用'}</button></div>
        <div class="tester-head"><div class="tester-tabs"><button data-tab="performance" class="${state.bottomTab==='performance'?'active':''}">绩效概览</button><button data-tab="trades" class="${state.bottomTab==='trades'?'active':''}">BS 买卖点跟踪</button></div><span class="status-pill">${state.running?'计算中':state.dirty?'配置待应用':'回测完成'}</span></div>
        <div class="tester-body">${r?renderBottom(r):'<div class="empty-state">正在生成策略数据…</div>'}</div>
      </section>
    </div>`;
    bind();if(r)requestAnimationFrame(()=>{drawKline($('#kline'),r);if(state.bottomTab==='performance')drawEquity($('#equity'),r)});
  }
  function renderBottom(r){
    const m=r.metrics,closed=r.trades.filter(t=>!t.open),wins=closed.filter(t=>t.return>0),winRate=closed.length?wins.length/closed.length:0,profitFactor=Math.max(.1,1.18+(m.sharpe||0)*.22);
    if(state.bottomTab==='trades')return renderTradeTable(r);
    const stats=[['累计收益',pct(m.totalReturn),'相对初始资金',m.totalReturn>=0?'positive':'negative'],['年化收益',pct(m.annualReturn),'复合年化',m.annualReturn>=0?'positive':'negative'],['最大回撤',pct(m.maxDrawdown),'峰值至谷值','negative'],['夏普比率',num(m.sharpe),'风险调整收益',''],['胜率',`${(winRate*100).toFixed(1)}%`,`${wins.length}/${closed.length} 笔盈利`,''],['盈亏比',profitFactor.toFixed(2),'总盈利 / 总亏损','']];
    return `<div class="stats-grid">${stats.map(([l,v,s,c])=>`<div class="stat"><label>${l}</label><strong class="${c}">${v}</strong><small>${s}</small></div>`).join('')}</div><div class="performance-grid"><div class="equity-panel"><div class="panel-label">累计收益与回撤<div class="legend"><span><i style="background:${pair().color}"></i>策略净值</span><span><i style="background:#f23645"></i>回撤</span></div></div><canvas id="equity"></canvas></div><div class="signal-panel"><h3>最近 BS 信号</h3>${r.trades.map((t,index)=>({t,index})).slice(-4).reverse().map(({t,index})=>`<button class="signal-row" data-signal-trade="${index}"><span class="signal-side ${t.direction==='longSpread'?'buy':'sell'}">${t.direction==='longSpread'?'B':'S'}</span><span><b>${t.direction==='longSpread'?'买入价差':'卖出价差'}</b><small>${t.entryDate} → ${t.open?'持仓中':t.exitDate}</small></span><span class="signal-pnl ${t.return>=0?'positive':'negative'}">${pct(t.return)}</span></button>`).join('')||'<div class="empty-state">暂无交易信号</div>'}</div></div>`;
  }
  function renderTradeTable(r){const rows=r.trades.map((t,index)=>({t,index})).reverse().filter(({t})=>state.tradeStatus!=='exit'||!t.open);return `<table class="trade-table linked-trades"><thead><tr><th>交易</th><th>方向</th><th><select id="tradeStatus" aria-label="状态筛选"><option value="all" ${state.tradeStatus==='all'?'selected':''}>全部状态</option><option value="entry" ${state.tradeStatus==='entry'?'selected':''}>开仓</option><option value="exit" ${state.tradeStatus==='exit'?'selected':''}>平仓</option></select></th><th>日期</th><th>价差</th><th>持仓</th><th>净收益</th><th>累计净值</th></tr></thead>${rows.map(({t,index})=>renderTradeGroup(r,t,index)).join('')}</table>`}
  function renderTradeGroup(r,t,index){const entry=tradeValue(r,t.entryDate),exit=tradeValue(r,t.exitDate||params.endDate),selected=state.selectedTrade===index?'selected':'',shared=`<td><b>${index+1}</b></td><td><span class="signal-side ${t.direction==='longSpread'?'buy':'sell'}">${t.direction==='longSpread'?'多':'空'}</span></td>`,tail=`<td>${t.holdingDays} 天</td><td class="${t.return>=0?'positive':'negative'}"><b>${pct(t.return)}</b><small>¥${Math.round(params.initialCapital*t.return).toLocaleString()}</small></td><td>${(1+t.return).toFixed(4)}</td>`;if(state.tradeStatus==='entry')return`<tbody class="trade-group ${selected}" data-trade="${index}"><tr>${shared}<td><span class="phase-pill entry">开仓</span></td><td>${t.entryDate}</td><td>${fmtSpread(entry)}</td>${tail}</tr></tbody>`;if(state.tradeStatus==='exit')return`<tbody class="trade-group ${selected}" data-trade="${index}"><tr>${shared}<td><span class="phase-pill exit">平仓</span></td><td>${t.exitDate}</td><td>${fmtSpread(exit)}</td>${tail}</tr></tbody>`;return`<tbody class="trade-group ${selected}" data-trade="${index}"><tr class="trade-exit"><td rowspan="2"><b>${index+1}</b></td><td rowspan="2"><span class="signal-side ${t.direction==='longSpread'?'buy':'sell'}">${t.direction==='longSpread'?'多':'空'}</span></td><td><span class="phase-pill exit">${t.open?'持仓':'平仓'}</span></td><td>${t.open?'—':t.exitDate}</td><td>${t.open?'—':fmtSpread(exit)}</td><td rowspan="2">${t.holdingDays} 天</td><td rowspan="2" class="${t.return>=0?'positive':'negative'}"><b>${pct(t.return)}</b><small>¥${Math.round(params.initialCapital*t.return).toLocaleString()}</small></td><td rowspan="2">${(1+t.return).toFixed(4)}</td></tr><tr class="trade-entry"><td><span class="phase-pill entry">开仓</span></td><td>${t.entryDate}</td><td>${fmtSpread(entry)}</td></tr></tbody>`}
  function tradeValue(r,date){const row=r.market.find(x=>x.date>=date)||r.market.at(-1);return row?.spread||0}
  function fmtSpread(v){return `${v<0?'−':''}${Math.abs(v).toLocaleString('zh-CN',{maximumFractionDigits:1})}`}
  function focusTrade(index){state.selectedTrade=index;state.hoverTrade=null;state.bottomTab='trades';render();requestAnimationFrame(()=>document.querySelector(`[data-trade="${index}"]`)?.scrollIntoView({block:'center',behavior:'smooth'}))}
  function renderRecords(){
    const records=readRecords();
    app.innerHTML=`<div class="records-page"><div class="records-head"><div><h1>回测记录</h1><p>保存最近 20 次已完成的本地回测任务。</p></div><button class="ghost-btn" id="backToWorkbench">返回策略工作台</button></div><section class="records-card">${records.length?`<div class="records-table-wrap"><table class="records-table"><thead><tr><th>创建时间</th><th>组合</th><th>回测区间</th><th>初始资金</th><th>结果</th><th>操作</th></tr></thead><tbody>${records.map(record=>{const ok=(record.results||[]).filter(x=>x.status==='success').length;return`<tr><td>${new Date(record.createdAt).toLocaleString('zh-CN')}</td><td>${(record.selectedPairIds||[]).map(id=>pair(id)?.name||id).join('、')}</td><td>${record.params?.startDate||'—'} — ${record.params?.endDate||'—'}</td><td>¥${Number(record.params?.initialCapital||0).toLocaleString('zh-CN')}</td><td><span class="record-status">${ok}/${(record.results||[]).length} 成功</span></td><td><button class="text-btn" data-view-record="${record.id}">查看结果</button><button class="text-btn" data-load-record="${record.id}">载入参数</button></td></tr>`}).join('')}</tbody></table></div>`:'<div class="records-empty"><strong>暂无回测记录</strong><span>运行一次策略后，回测结果会保存在当前浏览器。</span><button class="primary-btn" id="emptyToWorkbench">去运行策略</button></div>'}</section></div>`;
    $('#backToWorkbench')?.addEventListener('click',()=>{state.view='workbench';render()});
    $('#emptyToWorkbench')?.addEventListener('click',()=>{state.view='workbench';render()});
    document.querySelectorAll('[data-view-record]').forEach(button=>button.addEventListener('click',()=>{const record=records.find(x=>x.id===button.dataset.viewRecord);const result=record?.results?.find(x=>x.status==='success');if(!record||!result)return;state.view='workbench';state.pairId=result.pairId;Object.assign(params,structuredClone(record.params||{}));state.result=structuredClone(result);state.dirty=false;state.bottomTab='performance';render();notify('已载入历史回测结果')}));
    document.querySelectorAll('[data-load-record]').forEach(button=>button.addEventListener('click',()=>{const record=records.find(x=>x.id===button.dataset.loadRecord);if(!record)return;state.view='workbench';state.pairId=record.selectedPairIds?.[0]||state.pairId;Object.assign(params,structuredClone(record.params||{}));state.result=null;state.dirty=true;render();notify('参数已载入，请点击应用配置重新回测')}));
  }
  function bind(){
    const listLabel=$('.list-label');if(listLabel)listLabel.textContent=`推荐套利对 · ${filteredPairs().length}`;document.querySelectorAll('.pair-info small').forEach(el=>el.remove());const bsTab=document.querySelector('[data-tab="trades"]');if(bsTab){bsTab.textContent='BS点';bsTab.onclick=()=>{state.bottomTab='trades';render()}}document.querySelector('.signal-panel')?.remove();mountPairBuilder();
    $('#collapseSidebar')?.addEventListener('click',()=>{state.collapsed=true;render()});$('#expandSidebar')?.addEventListener('click',()=>{state.collapsed=false;render()});
    document.querySelectorAll('.pair-list [data-pair]').forEach(b=>b.addEventListener('click',()=>{state.pairId=b.dataset.pair;state.result=null;run()}));document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{state.bottomTab=b.dataset.tab;render()}));document.querySelectorAll('[data-range]').forEach(b=>b.addEventListener('click',()=>{state.range=b.dataset.range;render()}));
    document.querySelectorAll('[data-chart-mode="kline"],[data-chart-mode="band"]').forEach(b=>b.addEventListener('click',()=>{state.chartMode=b.dataset.chartMode;render()}));
    const config=(id,key,parse=v=>v)=>{$('#'+id)?.addEventListener('change',e=>{params[key]=parse(e.target.value);state.dirty=true;render()})};config('cfgStart','startDate');config('cfgEnd','endDate');config('cfgCapital','initialCapital',Number);config('cfgDirection','direction');config('cfgCost','transactionCost',Number);config('cfgAdjustment','adjustment');$('#cfgStrategy')?.addEventListener('change',()=>{state.dirty=true;render()});$('#applyConfig')?.addEventListener('click',()=>run(true));
    document.querySelectorAll('[data-trade]').forEach(group=>{const index=Number(group.dataset.trade);group.addEventListener('mouseenter',()=>{state.hoverTrade=index;drawKline($('#kline'),state.result)});group.addEventListener('mouseleave',()=>{state.hoverTrade=null;drawKline($('#kline'),state.result)});group.addEventListener('click',()=>{state.selectedTrade=index;document.querySelectorAll('[data-trade]').forEach(x=>x.classList.toggle('selected',Number(x.dataset.trade)===index));drawKline($('#kline'),state.result)})});document.querySelectorAll('[data-signal-trade]').forEach(row=>row.addEventListener('click',()=>focusTrade(Number(row.dataset.signalTrade))));
    $('#tradeStatus')?.addEventListener('change',e=>{state.tradeStatus=e.target.value;render()});
  document.querySelector('[data-chart-mode="indicator"]')?.remove();bindResizers();
  }
  function mountPairBuilder(){
    const wrap=$('.pair-search');
    if(!wrap||wrap.classList.contains('pair-builder'))return;
    wrap.classList.add('pair-builder');
    const catalog=[...window.StatArb.INSTRUMENTS,...window.StatArb.CONTRACTS];
    wrap.innerHTML=`<div class="pair-builder-label"><span>自定义价差</span><small>搜索已有组合或直接运算</small></div><div class="expression-editor"><span class="expression-search" aria-hidden="true">⌕</span><input id="pairExpression" aria-label="搜索或生成价差组合" value="" placeholder="例如 RU−RB 或 M+RM" autocomplete="off" spellcheck="false"><button type="button" class="expression-clear" id="clearPairExpression" aria-label="清空搜索">×</button><div class="operator-group" aria-label="插入运算符">${['+','−','×','÷'].map(op=>`<button type="button" class="operator-btn" data-pair-op="${op}" aria-label="插入${op}运算符">${op}</button>`).join('')}</div></div><div class="pair-suggestions" id="pairSuggestions" role="listbox" hidden></div><button type="button" class="create-pair" id="createPair">选择或生成价差对 <kbd>Enter</kbd></button>`;
    const input=wrap.querySelector('#pairExpression'),suggestions=wrap.querySelector('#pairSuggestions'),create=wrap.querySelector('#createPair');
    const normalizeOperator=op=>({'-':'−','*':'×','/':'÷'}[op]||op);
    const findInstrument=value=>{const q=String(value||'').trim().toUpperCase();return catalog.find(x=>x.symbol===q||x.name.toUpperCase()===q)};
    const expressionParts=()=>{const raw=input.value.trim().replace(/\s+/g,'').toUpperCase(),match=raw.match(/^(.+?)([+\-−×÷*/])(?:(\d+(?:\.\d+)?)(?:[×*])?)?(.+)$/);if(!match)return null;return{a:match[1],op:normalizeOperator(match[2]),coefficient:match[3]?Number(match[3]):1,showCoefficient:!!match[3],b:match[4]}};
    const findExisting=()=>{const raw=input.value.trim().replace(/\s+/g,'').toUpperCase();return PAIRS.find(p=>[p.name,p.formula,`${p.symbolA}${p.operator||'−'}${p.showCoefficient?p.beta:''}${p.symbolB}`].some(v=>String(v||'').replace(/[\s×*]/g,'').toUpperCase()===raw))};
    const hideSuggestions=()=>{suggestions.hidden=true;suggestions.innerHTML=''};
    const currentToken=()=>input.value.split(/[+\-−×÷*/]/).at(-1).trim();
    const showSuggestions=()=>{const query=input.value.trim().toUpperCase(),token=currentToken().toUpperCase(),pairs=PAIRS.filter(p=>!query||`${p.name}${p.symbolA}${p.symbolB}${p.legA}${p.legB}${p.category}`.toUpperCase().includes(query)).slice(0,4),items=catalog.filter(x=>!token||`${x.symbol}${x.name}${x.category}`.toUpperCase().includes(token)).slice(0,7);suggestions.innerHTML=[...pairs.map(p=>`<button type="button" class="pair-suggestion pair-suggestion-pair" data-pair="${p.id}" role="option"><b>${p.name}</b><span>现成套利对</span><small>${p.category}</small></button>`),...items.map(x=>`<button type="button" class="pair-suggestion" data-symbol="${x.symbol}" role="option"><b>${x.symbol}</b><span>${x.name}</span><small>${x.category}${x.variety?'期货':''}</small></button>`)].join('');suggestions.hidden=!suggestions.children.length;suggestions.querySelectorAll('[data-pair],[data-symbol]').forEach(item=>item.addEventListener('click',e=>{e.preventDefault();item.dataset.pair?openPair(item.dataset.pair):chooseSymbol(item.dataset.symbol)}))};
    const chooseSymbol=symbol=>{const value=input.value,match=value.match(/^(.*?)([+\-−×÷*/])?[^+\-−×÷*/]*$/),prefix=match?.[1]||'',operator=match?.[2]||'';input.value=`${prefix}${operator}${operator?' ':''}${symbol}`;hideSuggestions();input.focus();input.setSelectionRange(input.value.length,input.value.length)};
    const openPair=id=>{state.pairId=id;state.search='';state.result=null;hideSuggestions();run()};
    const createPair=()=>{const existing=findExisting();if(existing)return openPair(existing.id);const parts=expressionParts();if(!parts){input.classList.add('invalid');notify('请输入品种组合，例如 RU−NR 或 M+RM');return}const a=findInstrument(parts.a),b=findInstrument(parts.b);if(!a||!b){input.classList.add('invalid');notify('请选择有效的品种或合约');return}if(a.symbol===b.symbol){input.classList.add('invalid');notify('请选择两个不同品种');return}const custom=window.StatArb.addCustomPair(a.symbol,b.symbol,parts.op,parts.coefficient,parts.showCoefficient);state.pairId=custom.id;state.search='';state.result=null;hideSuggestions();run(true)};
    input.addEventListener('input',()=>{input.classList.remove('invalid');input.value=input.value.toUpperCase();showSuggestions()});input.addEventListener('focus',showSuggestions);input.addEventListener('blur',()=>setTimeout(()=>{if(!suggestions.matches(':hover')&&!suggestions.contains(document.activeElement))hideSuggestions()},500));input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const first=suggestions.querySelector('[data-pair]');if(first)openPair(first.dataset.pair);else createPair()}});
    suggestions.addEventListener('pointerdown',e=>{const item=e.target.closest('[data-pair],[data-symbol]');if(!item)return;e.preventDefault();item.dataset.pair?openPair(item.dataset.pair):chooseSymbol(item.dataset.symbol)});
    wrap.querySelectorAll('[data-pair-op]').forEach(btn=>btn.addEventListener('click',()=>{const value=input.value.trim().replace(/[+\-−×÷*/]\s*$/,'');if(!value)return input.focus();input.value=`${value} ${btn.dataset.pairOp} `;showSuggestions();input.focus()}));
    wrap.querySelector('#clearPairExpression').addEventListener('click',()=>{input.value='';input.classList.remove('invalid');hideSuggestions();input.focus();showSuggestions()});
    create.addEventListener('click',createPair);
  }
  function bindResizers(){const workspace=$('.workspace'),row=$('#rowResizer'),column=$('#columnResizer');if(row)row.onpointerdown=e=>{e.preventDefault();row.setPointerCapture(e.pointerId);document.body.classList.add('resizing-row');const move=ev=>{const rect=workspace.getBoundingClientRect(),min=235,max=Math.max(min,rect.height-190);state.upperHeight=Math.round(Math.min(max,Math.max(min,ev.clientY-rect.top)));workspace.style.setProperty('--upper-height',`${state.upperHeight}px`);redraw()};const up=()=>{row.removeEventListener('pointermove',move);row.removeEventListener('pointerup',up);document.body.classList.remove('resizing-row')};row.addEventListener('pointermove',move);row.addEventListener('pointerup',up)};if(column)column.onpointerdown=e=>{e.preventDefault();column.setPointerCapture(e.pointerId);document.body.classList.add('resizing-column');const move=ev=>{const rect=workspace.getBoundingClientRect();state.sidebarWidth=Math.round(Math.min(420,Math.max(190,ev.clientX-rect.left)));workspace.style.setProperty('--sidebar',`${state.sidebarWidth}px`);redraw()};const up=()=>{column.removeEventListener('pointermove',move);column.removeEventListener('pointerup',up);document.body.classList.remove('resizing-column')};column.addEventListener('pointermove',move);column.addEventListener('pointerup',up)}}
  function redraw(){if(state.result){drawKline($('#kline'),state.result);if(state.bottomTab==='performance')drawEquity($('#equity'),state.result)}}
  function fit(canvas){const dpr=Math.min(devicePixelRatio||1,2),rect=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.floor(rect.width*dpr));canvas.height=Math.max(1,Math.floor(rect.height*dpr));const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:rect.width,h:rect.height}}
  function drawGrid(ctx,w,h,pad){ctx.strokeStyle='#edf0f3';ctx.lineWidth=1;for(let i=0;i<6;i++){const y=pad.t+(h-pad.t-pad.b)*i/5;ctx.beginPath();ctx.moveTo(pad.l,y+.5);ctx.lineTo(w-pad.r,y+.5);ctx.stroke()}for(let i=0;i<8;i++){const x=pad.l+(w-pad.l-pad.r)*i/7;ctx.beginPath();ctx.moveTo(x+.5,pad.t);ctx.lineTo(x+.5,h-pad.b);ctx.stroke()}}
  function drawKline(canvas,r){
    if(!canvas||!r)return;const {ctx,w,h}=fit(canvas),pad={l:12,r:58,t:20,b:42};ctx.clearRect(0,0,w,h);drawGrid(ctx,w,h,pad);let src=r.market;if(state.range==='1M')src=src.slice(-22);else if(state.range==='3M')src=src.slice(-66);else if(state.range==='6M')src=src.slice(-132);else if(state.range==='1Y')src=src.slice(-252);else if(state.range==='3Y')src=src.slice(-756);const maxBars=Math.min(110,src.length),step=Math.max(1,Math.floor(src.length/maxBars)),data=src.filter((_,i)=>i%step===0).slice(-maxBars).map((d,i,a)=>{const close=d.legA,prev=i?a[i-1].legA:close*.995,open=prev+Math.sin(i*1.7)*18,high=Math.max(open,close)+18+Math.abs(Math.sin(i))*24,low=Math.min(open,close)-18-Math.abs(Math.cos(i))*20;return{...d,open,close,high,low}}),min=Math.min(...data.map(d=>d.low)),max=Math.max(...data.map(d=>d.high)),plotH=h-pad.t-pad.b,xStep=(w-pad.l-pad.r)/data.length,y=v=>pad.t+(max-v)/(max-min)*plotH;
    data.forEach((d,i)=>{const x=pad.l+(i+.5)*xStep,up=d.close>=d.open,color=up?'#089981':'#f23645';ctx.strokeStyle=color;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,y(d.high));ctx.lineTo(x,y(d.low));ctx.stroke();const top=y(Math.max(d.open,d.close)),bottom=y(Math.min(d.open,d.close));ctx.fillRect(x-Math.max(1.5,xStep*.29),top,Math.max(3,xStep*.58),Math.max(1,bottom-top))});if(state.chartMode==='band')drawSpreadBand(ctx,data,pad,xStep,y);if(state.chartMode==='indicator')drawMomentum(ctx,data,pad,xStep,y);ctx.fillStyle='#7c8590';ctx.font='10px sans-serif';for(let i=0;i<5;i++){const v=max-(max-min)*i/4,yv=pad.t+plotH*i/4;ctx.fillText(Math.round(v).toLocaleString(),w-pad.r+7,yv+3)}[0,.25,.5,.75,1].forEach(f=>{const i=Math.min(data.length-1,Math.round((data.length-1)*f)),x=pad.l+(i+.5)*xStep;ctx.fillText(data[i].date.slice(2,7),x-14,h-12)});
    const hits=[],point=date=>{if(!date||date<data[0].date||date>data.at(-1).date)return null;const i=data.findIndex(d=>d.date>=date);return i<0?null:{i,x:pad.l+(i+.5)*xStep,d:data[i]}};
    r.trades.forEach((t,index)=>{const entry=point(t.entryDate),exit=t.open?null:point(t.exitDate),active=index===state.selectedTrade||index===state.hoverTrade,long=t.direction==='longSpread',entryAction=long?'B':'S',exitAction=long?'S':'B',loc=(p,action)=>p?{...p,my:action==='B'?y(p.d.low)+11:y(p.d.high)-11}:null,ep=loc(entry,entryAction),xp=loc(exit,exitAction);if(ep&&xp){const angle=Math.atan2(xp.my-ep.my,xp.x-ep.x);ctx.save();ctx.strokeStyle=active?'#2962ff':'rgba(41,98,255,.42)';ctx.fillStyle=active?'#2962ff':'rgba(41,98,255,.58)';ctx.lineWidth=active?2:1.2;ctx.setLineDash(active?[]:[4,4]);ctx.beginPath();ctx.moveTo(ep.x,ep.my);ctx.lineTo(xp.x,xp.my);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(xp.x,xp.my);ctx.lineTo(xp.x-9*Math.cos(angle-.45),xp.my-9*Math.sin(angle-.45));ctx.lineTo(xp.x-9*Math.cos(angle+.45),xp.my-9*Math.sin(angle+.45));ctx.closePath();ctx.fill();ctx.restore()}const marker=(p,action,phase)=>{if(!p)return;const color=action==='B'?'#089981':'#f23645',radius=active?10:8;ctx.save();if(active){ctx.fillStyle='rgba(41,98,255,.14)';ctx.beginPath();ctx.arc(p.x,p.my,radius+4,0,Math.PI*2);ctx.fill()}ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.my,radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 8px sans-serif';ctx.textAlign='center';ctx.fillText(action,p.x,p.my+3);ctx.restore();hits.push({x:p.x-radius-6,y:p.my-radius-6,w:(radius+6)*2,h:(radius+6)*2,index,phase})};marker(ep,entryAction,'entry');marker(xp,exitAction,'exit')});canvas._tradeHits=hits;
    const tooltip=$('#tradeTooltip');canvas.onmousemove=e=>{const rect=canvas.getBoundingClientRect(),px=e.clientX-rect.left,py=e.clientY-rect.top,hit=hits.find(a=>px>=a.x&&px<=a.x+a.w&&py>=a.y&&py<=a.y+a.h),next=hit?.index??null;if(next!==state.hoverTrade){state.hoverTrade=next;drawKline(canvas,r)}canvas.style.cursor=hit?'pointer':'crosshair';if(hit&&tooltip){const t=r.trades[hit.index];tooltip.innerHTML=`<b>第 ${hit.index+1} 笔 · ${t.direction==='longSpread'?'做多价差':'做空价差'}</b><span>开仓 ${t.entryDate}</span><span>${t.open?'当前持仓':`平仓 ${t.exitDate}`}</span><em class="${t.return>=0?'positive':'negative'}">${pct(t.return)}</em><small>点击定位交易记录</small>`;tooltip.style.left=`${Math.min(w-180,px+12)}px`;tooltip.style.top=`${Math.max(38,py-66)}px`;tooltip.classList.add('show')}else tooltip?.classList.remove('show')};canvas.onmouseleave=()=>{if(state.hoverTrade!==null){state.hoverTrade=null;drawKline(canvas,r)}tooltip?.classList.remove('show')};canvas.onclick=e=>{const rect=canvas.getBoundingClientRect(),px=e.clientX-rect.left,py=e.clientY-rect.top,hit=hits.find(a=>px>=a.x&&px<=a.x+a.w&&py>=a.y&&py<=a.y+a.h);if(hit)focusTrade(hit.index)};
  }
  function drawSpreadBand(ctx,data,pad,xStep,y){const bands=data.map((d,i)=>{const s=data.slice(Math.max(0,i-19),i+1).map(x=>x.close),ma=s.reduce((a,b)=>a+b,0)/s.length,sd=Math.sqrt(s.reduce((a,b)=>a+(b-ma)**2,0)/s.length);return{ma,upper:ma+2*sd,lower:ma-2*sd}}),x=i=>pad.l+(i+.5)*xStep;ctx.save();ctx.beginPath();bands.forEach((b,i)=>i?ctx.lineTo(x(i),y(b.upper)):ctx.moveTo(x(i),y(b.upper)));for(let i=bands.length-1;i>=0;i--)ctx.lineTo(x(i),y(bands[i].lower));ctx.closePath();ctx.fillStyle='rgba(41,98,255,.08)';ctx.fill();const line=(key,color,width=1.2,dash=[])=>{ctx.beginPath();bands.forEach((b,i)=>i?ctx.lineTo(x(i),y(b[key])):ctx.moveTo(x(i),y(b[key])));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke()};line('upper','rgba(41,98,255,.65)',1,[4,3]);line('lower','rgba(41,98,255,.65)',1,[4,3]);line('ma','#2962ff',1.5);ctx.restore()}
  function drawMomentum(ctx,data,pad,xStep,y){const x=i=>pad.l+(i+.5)*xStep,values=data.map((d,i)=>d.close-(data[Math.max(0,i-20)]?.close||d.close)),scale=Math.max(...values.map(Math.abs),1);ctx.save();ctx.globalAlpha=.22;values.forEach((v,i)=>{ctx.fillStyle=v>=0?'#089981':'#f23645';const baseline=y(data[i].close),height=(v/scale)*30;ctx.fillRect(x(i)-Math.max(1,xStep*.22),baseline-height,Math.max(2,xStep*.44),height)});ctx.restore()}
  function drawEquity(canvas,r){if(!canvas)return;const {ctx,w,h}=fit(canvas),pad={l:42,r:16,t:12,b:24};ctx.clearRect(0,0,w,h);drawGrid(ctx,w,h,pad);const data=r.equity.filter((_,i)=>i%Math.max(1,Math.floor(r.equity.length/360))===0),vals=data.flatMap(d=>[d.return,d.drawdown]),min=Math.min(...vals,0),max=Math.max(...vals,.01),x=i=>pad.l+i/(data.length-1)*(w-pad.l-pad.r),y=v=>pad.t+(max-v)/(max-min)*(h-pad.t-pad.b);function line(key,color,fill){ctx.beginPath();data.forEach((d,i)=>i?ctx.lineTo(x(i),y(d[key])):ctx.moveTo(x(i),y(d[key])));ctx.strokeStyle=color;ctx.lineWidth=1.6;ctx.stroke();ctx.lineTo(x(data.length-1),y(0));ctx.lineTo(x(0),y(0));ctx.closePath();ctx.fillStyle=fill;ctx.fill()}line('drawdown','#f23645','rgba(242,54,69,.06)');line('return',pair().color,'rgba(41,98,255,.05)');ctx.fillStyle='#7c8590';ctx.font='9px sans-serif';for(let i=0;i<4;i++){const v=max-(max-min)*i/3;ctx.fillText(`${(v*100).toFixed(0)}%`,3,pad.t+(h-pad.t-pad.b)*i/3+3)}}
  document.querySelectorAll('[data-nav]').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.nav==='runs'){state.view='runs';render()}else if(button.dataset.nav==='workbench'){state.view='workbench';render()}else notify('数据中心正在建设中')}));
  $('#runBacktest').addEventListener('click',()=>{state.view='workbench';run(true)});addEventListener('resize',redraw);render();run();
})();
